export const ALUMNOS_MOCK = [
  {
    id: 1,
    nombre: "Juan",
    apellido: "Pérez",
    dni: "41234567",
    edad: 24,
    peso: 78,
    fechaInscripcion: "2026-03-10",
    experiencia: "entrenando",
    frecuencia: 4,
    estadoPago: "pagado",
  },
  {
    id: 2,
    nombre: "Lucía",
    apellido: "Gómez",
    dni: "39876543",
    edad: 29,
    peso: 62,
    fechaInscripcion: "2026-05-22",
    experiencia: "nuevo",
    frecuencia: null,
    estadoPago: "vencido",
  },
  {
    id: 3,
    nombre: "Martín",
    apellido: "Díaz",
    dni: "44567890",
    edad: 35,
    peso: 90,
    fechaInscripcion: "2025-11-02",
    experiencia: "entrenando",
    frecuencia: 3,
    estadoPago: "vencido",
  },
];
